/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AIActQuery = IDL.Record({
  'context' : IDL.Opt(IDL.Text),
  'question' : IDL.Text,
});
export const AIActResponse = IDL.Record({
  'complianceTips' : IDL.Opt(IDL.Text),
  'references' : IDL.Opt(IDL.Text),
  'answer' : IDL.Text,
});
export const CybersecurityResult = IDL.Record({
  'status' : IDL.Text,
  'recommendations' : IDL.Text,
  'score' : IDL.Nat,
  'vulnerabilities' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CybersecurityQuery = IDL.Record({
  'context' : IDL.Opt(IDL.Text),
  'question' : IDL.Text,
});
export const CybersecurityResponse = IDL.Record({
  'references' : IDL.Opt(IDL.Text),
  'answer' : IDL.Text,
  'securityTips' : IDL.Opt(IDL.Text),
});
export const Regulation = IDL.Variant({
  'usAIRegulations' : IDL.Null,
  'euAIAct' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ComplianceResult = IDL.Record({
  'status' : IDL.Text,
  'recommendations' : IDL.Text,
  'score' : IDL.Nat,
});
export const DocumentMetadata = IDL.Record({
  'id' : IDL.Text,
  'regulation' : Regulation,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'compliance' : IDL.Opt(ComplianceResult),
  'hash' : IDL.Vec(IDL.Nat8),
  'filename' : IDL.Text,
  'timestamp' : IDL.Int,
  'companyName' : IDL.Text,
});
export const RepositoryMetadata = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'cybersecurity' : IDL.Opt(CybersecurityResult),
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RiskCategory = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const RiskEvent = IDL.Record({
  'id' : IDL.Text,
  'issueType' : IDL.Text,
  'suggestedAction' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : RiskCategory,
  'severity' : IDL.Text,
  'riskScore' : IDL.Nat,
});
export const RiskAnalysis = IDL.Record({
  'recommendations' : IDL.Text,
  'summary' : IDL.Text,
  'events' : IDL.Vec(RiskEvent),
  'category' : RiskCategory,
  'currentScore' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addRepository' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'aiActAssistant' : IDL.Func([AIActQuery], [AIActResponse], []),
  'analyzeRepository' : IDL.Func([IDL.Text], [CybersecurityResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cybersecurityAssistant' : IDL.Func(
      [CybersecurityQuery],
      [CybersecurityResponse],
      [],
    ),
  'generateSDKSecret' : IDL.Func([], [IDL.Text], []),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(DocumentMetadata)], ['query']),
  'getAllRepositories' : IDL.Func([], [IDL.Vec(RepositoryMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplianceDashboard' : IDL.Func(
      [],
      [IDL.Vec(DocumentMetadata)],
      ['query'],
    ),
  'getCybersecurityDashboard' : IDL.Func(
      [],
      [IDL.Vec(RepositoryMetadata)],
      ['query'],
    ),
  'getExampleDocument' : IDL.Func([], [IDL.Opt(DocumentMetadata)], ['query']),
  'getExampleRepository' : IDL.Func(
      [],
      [IDL.Opt(RepositoryMetadata)],
      ['query'],
    ),
  'getRiskAnalysis' : IDL.Func([], [RiskAnalysis], ['query']),
  'getRiskEvents' : IDL.Func([], [IDL.Vec(RiskEvent)], ['query']),
  'getSDKSecret' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeGetOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
  'makePostOutcall' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'runRiskAnalysis' : IDL.Func([], [RiskAnalysis], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCompanyName' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateComplianceScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateCybersecurityScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'uploadDocument' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8), Regulation, ExternalBlob, IDL.Text],
      [IDL.Text],
      [],
    ),
  'verifyDocument' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Opt(DocumentMetadata)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AIActQuery = IDL.Record({
    'context' : IDL.Opt(IDL.Text),
    'question' : IDL.Text,
  });
  const AIActResponse = IDL.Record({
    'complianceTips' : IDL.Opt(IDL.Text),
    'references' : IDL.Opt(IDL.Text),
    'answer' : IDL.Text,
  });
  const CybersecurityResult = IDL.Record({
    'status' : IDL.Text,
    'recommendations' : IDL.Text,
    'score' : IDL.Nat,
    'vulnerabilities' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CybersecurityQuery = IDL.Record({
    'context' : IDL.Opt(IDL.Text),
    'question' : IDL.Text,
  });
  const CybersecurityResponse = IDL.Record({
    'references' : IDL.Opt(IDL.Text),
    'answer' : IDL.Text,
    'securityTips' : IDL.Opt(IDL.Text),
  });
  const Regulation = IDL.Variant({
    'usAIRegulations' : IDL.Null,
    'euAIAct' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ComplianceResult = IDL.Record({
    'status' : IDL.Text,
    'recommendations' : IDL.Text,
    'score' : IDL.Nat,
  });
  const DocumentMetadata = IDL.Record({
    'id' : IDL.Text,
    'regulation' : Regulation,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'compliance' : IDL.Opt(ComplianceResult),
    'hash' : IDL.Vec(IDL.Nat8),
    'filename' : IDL.Text,
    'timestamp' : IDL.Int,
    'companyName' : IDL.Text,
  });
  const RepositoryMetadata = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'cybersecurity' : IDL.Opt(CybersecurityResult),
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RiskCategory = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RiskEvent = IDL.Record({
    'id' : IDL.Text,
    'issueType' : IDL.Text,
    'suggestedAction' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : RiskCategory,
    'severity' : IDL.Text,
    'riskScore' : IDL.Nat,
  });
  const RiskAnalysis = IDL.Record({
    'recommendations' : IDL.Text,
    'summary' : IDL.Text,
    'events' : IDL.Vec(RiskEvent),
    'category' : RiskCategory,
    'currentScore' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addRepository' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'aiActAssistant' : IDL.Func([AIActQuery], [AIActResponse], []),
    'analyzeRepository' : IDL.Func([IDL.Text], [CybersecurityResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cybersecurityAssistant' : IDL.Func(
        [CybersecurityQuery],
        [CybersecurityResponse],
        [],
      ),
    'generateSDKSecret' : IDL.Func([], [IDL.Text], []),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(DocumentMetadata)], ['query']),
    'getAllRepositories' : IDL.Func(
        [],
        [IDL.Vec(RepositoryMetadata)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplianceDashboard' : IDL.Func(
        [],
        [IDL.Vec(DocumentMetadata)],
        ['query'],
      ),
    'getCybersecurityDashboard' : IDL.Func(
        [],
        [IDL.Vec(RepositoryMetadata)],
        ['query'],
      ),
    'getExampleDocument' : IDL.Func([], [IDL.Opt(DocumentMetadata)], ['query']),
    'getExampleRepository' : IDL.Func(
        [],
        [IDL.Opt(RepositoryMetadata)],
        ['query'],
      ),
    'getRiskAnalysis' : IDL.Func([], [RiskAnalysis], ['query']),
    'getRiskEvents' : IDL.Func([], [IDL.Vec(RiskEvent)], ['query']),
    'getSDKSecret' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeGetOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
    'makePostOutcall' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'runRiskAnalysis' : IDL.Func([], [RiskAnalysis], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCompanyName' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateComplianceScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateCybersecurityScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'uploadDocument' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8), Regulation, ExternalBlob, IDL.Text],
        [IDL.Text],
        [],
      ),
    'verifyDocument' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(DocumentMetadata)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };