/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIActQuery { 'context' : [] | [string], 'question' : string }
export interface AIActResponse {
  'complianceTips' : [] | [string],
  'references' : [] | [string],
  'answer' : string,
}
export interface ComplianceResult {
  'status' : string,
  'recommendations' : string,
  'score' : bigint,
}
export interface CybersecurityQuery {
  'context' : [] | [string],
  'question' : string,
}
export interface CybersecurityResponse {
  'references' : [] | [string],
  'answer' : string,
  'securityTips' : [] | [string],
}
export interface CybersecurityResult {
  'status' : string,
  'recommendations' : string,
  'score' : bigint,
  'vulnerabilities' : string,
}
export interface DocumentMetadata {
  'id' : string,
  'regulation' : Regulation,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'compliance' : [] | [ComplianceResult],
  'hash' : Uint8Array,
  'filename' : string,
  'timestamp' : bigint,
  'companyName' : string,
}
export type ExternalBlob = Uint8Array;
export type Regulation = { 'usAIRegulations' : null } |
  { 'euAIAct' : null };
export interface RepositoryMetadata {
  'id' : string,
  'url' : string,
  'owner' : Principal,
  'name' : string,
  'cybersecurity' : [] | [CybersecurityResult],
  'timestamp' : bigint,
}
export interface RiskAnalysis {
  'recommendations' : string,
  'summary' : string,
  'events' : Array<RiskEvent>,
  'category' : RiskCategory,
  'currentScore' : bigint,
}
export type RiskCategory = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface RiskEvent {
  'id' : string,
  'issueType' : string,
  'suggestedAction' : string,
  'description' : string,
  'timestamp' : bigint,
  'category' : RiskCategory,
  'severity' : string,
  'riskScore' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addRepository' : ActorMethod<[string, string], string>,
  'aiActAssistant' : ActorMethod<[AIActQuery], AIActResponse>,
  'analyzeRepository' : ActorMethod<[string], CybersecurityResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cybersecurityAssistant' : ActorMethod<
    [CybersecurityQuery],
    CybersecurityResponse
  >,
  'generateSDKSecret' : ActorMethod<[], string>,
  'getAllDocuments' : ActorMethod<[], Array<DocumentMetadata>>,
  'getAllRepositories' : ActorMethod<[], Array<RepositoryMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplianceDashboard' : ActorMethod<[], Array<DocumentMetadata>>,
  'getCybersecurityDashboard' : ActorMethod<[], Array<RepositoryMetadata>>,
  'getExampleDocument' : ActorMethod<[], [] | [DocumentMetadata]>,
  'getExampleRepository' : ActorMethod<[], [] | [RepositoryMetadata]>,
  'getRiskAnalysis' : ActorMethod<[], RiskAnalysis>,
  'getRiskEvents' : ActorMethod<[], Array<RiskEvent>>,
  'getSDKSecret' : ActorMethod<[], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeGetOutcall' : ActorMethod<[string], string>,
  'makePostOutcall' : ActorMethod<[string, string], string>,
  'runRiskAnalysis' : ActorMethod<[], RiskAnalysis>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCompanyName' : ActorMethod<[string, string], undefined>,
  'updateComplianceScore' : ActorMethod<[string, bigint], undefined>,
  'updateCybersecurityScore' : ActorMethod<[string, bigint], undefined>,
  'uploadDocument' : ActorMethod<
    [string, Uint8Array, Regulation, ExternalBlob, string],
    string
  >,
  'verifyDocument' : ActorMethod<[Uint8Array], [] | [DocumentMetadata]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];