/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AIActQuery {
    context?: string;
    question: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface RiskEvent {
    id: string;
    issueType: string;
    suggestedAction: string;
    description: string;
    timestamp: bigint;
    category: RiskCategory;
    severity: string;
    riskScore: bigint;
}
export interface CybersecurityQuery {
    context?: string;
    question: string;
}
export interface DocumentMetadata {
    id: string;
    regulation: Regulation;
    owner: Principal;
    blob: ExternalBlob;
    compliance?: ComplianceResult;
    hash: Uint8Array;
    filename: string;
    timestamp: bigint;
    companyName: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RepositoryMetadata {
    id: string;
    url: string;
    owner: Principal;
    name: string;
    cybersecurity?: CybersecurityResult;
    timestamp: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface RiskAnalysis {
    recommendations: string;
    summary: string;
    events: Array<RiskEvent>;
    category: RiskCategory;
    currentScore: bigint;
}
export interface CybersecurityResult {
    status: string;
    recommendations: string;
    score: bigint;
    vulnerabilities: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CybersecurityResponse {
    references?: string;
    answer: string;
    securityTips?: string;
}
export interface AIActResponse {
    complianceTips?: string;
    references?: string;
    answer: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ComplianceResult {
    status: string;
    recommendations: string;
    score: bigint;
}
export interface UserProfile {
    name: string;
}
export enum Regulation {
    usAIRegulations = "usAIRegulations",
    euAIAct = "euAIAct"
}
export enum RiskCategory {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addRepository(name: string, url: string): Promise<string>;
    aiActAssistant(aiQuery: AIActQuery): Promise<AIActResponse>;
    analyzeRepository(repositoryId: string): Promise<CybersecurityResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cybersecurityAssistant(cyberQuery: CybersecurityQuery): Promise<CybersecurityResponse>;
    generateSDKSecret(): Promise<string>;
    getAllDocuments(): Promise<Array<DocumentMetadata>>;
    getAllRepositories(): Promise<Array<RepositoryMetadata>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComplianceDashboard(): Promise<Array<DocumentMetadata>>;
    getCybersecurityDashboard(): Promise<Array<RepositoryMetadata>>;
    getExampleDocument(): Promise<DocumentMetadata | null>;
    getExampleRepository(): Promise<RepositoryMetadata | null>;
    getRiskAnalysis(): Promise<RiskAnalysis>;
    getRiskEvents(): Promise<Array<RiskEvent>>;
    getSDKSecret(): Promise<string | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    makeGetOutcall(url: string): Promise<string>;
    makePostOutcall(url: string, body: string): Promise<string>;
    runRiskAnalysis(): Promise<RiskAnalysis>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCompanyName(documentId: string, newCompanyName: string): Promise<void>;
    updateComplianceScore(documentId: string, newScore: bigint): Promise<void>;
    updateCybersecurityScore(repositoryId: string, newScore: bigint): Promise<void>;
    uploadDocument(filename: string, hash: Uint8Array, regulation: Regulation, blob: ExternalBlob, companyName: string): Promise<string>;
    verifyDocument(hash: Uint8Array): Promise<DocumentMetadata | null>;
}
import type { AIActQuery as _AIActQuery, AIActResponse as _AIActResponse, ComplianceResult as _ComplianceResult, CybersecurityQuery as _CybersecurityQuery, CybersecurityResponse as _CybersecurityResponse, CybersecurityResult as _CybersecurityResult, DocumentMetadata as _DocumentMetadata, ExternalBlob as _ExternalBlob, Regulation as _Regulation, RepositoryMetadata as _RepositoryMetadata, RiskAnalysis as _RiskAnalysis, RiskCategory as _RiskCategory, RiskEvent as _RiskEvent, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addRepository(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addRepository(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRepository(arg0, arg1);
            return result;
        }
    }
    async aiActAssistant(arg0: AIActQuery): Promise<AIActResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.aiActAssistant(to_candid_AIActQuery_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AIActResponse_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.aiActAssistant(to_candid_AIActQuery_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AIActResponse_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async analyzeRepository(arg0: string): Promise<CybersecurityResult> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeRepository(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeRepository(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cybersecurityAssistant(arg0: CybersecurityQuery): Promise<CybersecurityResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.cybersecurityAssistant(to_candid_CybersecurityQuery_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CybersecurityResponse_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cybersecurityAssistant(to_candid_CybersecurityQuery_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CybersecurityResponse_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateSDKSecret(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSDKSecret();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSDKSecret();
            return result;
        }
    }
    async getAllDocuments(): Promise<Array<DocumentMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDocuments();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDocuments();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRepositories(): Promise<Array<RepositoryMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRepositories();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRepositories();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplianceDashboard(): Promise<Array<DocumentMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplianceDashboard();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplianceDashboard();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCybersecurityDashboard(): Promise<Array<RepositoryMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCybersecurityDashboard();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCybersecurityDashboard();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExampleDocument(): Promise<DocumentMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExampleDocument();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExampleDocument();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExampleRepository(): Promise<RepositoryMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExampleRepository();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExampleRepository();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiskAnalysis(): Promise<RiskAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskAnalysis();
                return from_candid_RiskAnalysis_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskAnalysis();
            return from_candid_RiskAnalysis_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiskEvents(): Promise<Array<RiskEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskEvents();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskEvents();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSDKSecret(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSDKSecret();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSDKSecret();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async makeGetOutcall(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.makeGetOutcall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeGetOutcall(arg0);
            return result;
        }
    }
    async makePostOutcall(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.makePostOutcall(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makePostOutcall(arg0, arg1);
            return result;
        }
    }
    async runRiskAnalysis(): Promise<RiskAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.runRiskAnalysis();
                return from_candid_RiskAnalysis_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runRiskAnalysis();
            return from_candid_RiskAnalysis_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCompanyName(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompanyName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompanyName(arg0, arg1);
            return result;
        }
    }
    async updateComplianceScore(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplianceScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplianceScore(arg0, arg1);
            return result;
        }
    }
    async updateCybersecurityScore(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCybersecurityScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCybersecurityScore(arg0, arg1);
            return result;
        }
    }
    async uploadDocument(arg0: string, arg1: Uint8Array, arg2: Regulation, arg3: ExternalBlob, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(arg0, arg1, to_candid_Regulation_n41(this._uploadFile, this._downloadFile, arg2), await to_candid_ExternalBlob_n43(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(arg0, arg1, to_candid_Regulation_n41(this._uploadFile, this._downloadFile, arg2), await to_candid_ExternalBlob_n43(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async verifyDocument(arg0: Uint8Array): Promise<DocumentMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyDocument(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyDocument(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AIActResponse_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIActResponse): AIActResponse {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_CybersecurityResponse_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CybersecurityResponse): CybersecurityResponse {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_DocumentMetadata_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentMetadata): Promise<DocumentMetadata> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Regulation_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Regulation): Regulation {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_RepositoryMetadata_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepositoryMetadata): RepositoryMetadata {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_RiskAnalysis_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskAnalysis): RiskAnalysis {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_RiskCategory_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskCategory): RiskCategory {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_RiskEvent_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskEvent): RiskEvent {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ComplianceResult]): ComplianceResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CybersecurityResult]): CybersecurityResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentMetadata]): Promise<DocumentMetadata | null> {
    return value.length === 0 ? null : await from_candid_DocumentMetadata_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RepositoryMetadata]): RepositoryMetadata | null {
    return value.length === 0 ? null : from_candid_RepositoryMetadata_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    complianceTips: [] | [string];
    references: [] | [string];
    answer: string;
}): {
    complianceTips?: string;
    references?: string;
    answer: string;
} {
    return {
        complianceTips: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.complianceTips)),
        references: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.references)),
        answer: value.answer
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    references: [] | [string];
    answer: string;
    securityTips: [] | [string];
}): {
    references?: string;
    answer: string;
    securityTips?: string;
} {
    return {
        references: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.references)),
        answer: value.answer,
        securityTips: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.securityTips))
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    regulation: _Regulation;
    owner: Principal;
    blob: _ExternalBlob;
    compliance: [] | [_ComplianceResult];
    hash: Uint8Array;
    filename: string;
    timestamp: bigint;
    companyName: string;
}): Promise<{
    id: string;
    regulation: Regulation;
    owner: Principal;
    blob: ExternalBlob;
    compliance?: ComplianceResult;
    hash: Uint8Array;
    filename: string;
    timestamp: bigint;
    companyName: string;
}> {
    return {
        id: value.id,
        regulation: from_candid_Regulation_n21(_uploadFile, _downloadFile, value.regulation),
        owner: value.owner,
        blob: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.blob),
        compliance: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.compliance)),
        hash: value.hash,
        filename: value.filename,
        timestamp: value.timestamp,
        companyName: value.companyName
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    owner: Principal;
    name: string;
    cybersecurity: [] | [_CybersecurityResult];
    timestamp: bigint;
}): {
    id: string;
    url: string;
    owner: Principal;
    name: string;
    cybersecurity?: CybersecurityResult;
    timestamp: bigint;
} {
    return {
        id: value.id,
        url: value.url,
        owner: value.owner,
        name: value.name,
        cybersecurity: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.cybersecurity)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recommendations: string;
    summary: string;
    events: Array<_RiskEvent>;
    category: _RiskCategory;
    currentScore: bigint;
}): {
    recommendations: string;
    summary: string;
    events: Array<RiskEvent>;
    category: RiskCategory;
    currentScore: bigint;
} {
    return {
        recommendations: value.recommendations,
        summary: value.summary,
        events: from_candid_vec_n36(_uploadFile, _downloadFile, value.events),
        category: from_candid_RiskCategory_n39(_uploadFile, _downloadFile, value.category),
        currentScore: value.currentScore
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    issueType: string;
    suggestedAction: string;
    description: string;
    timestamp: bigint;
    category: _RiskCategory;
    severity: string;
    riskScore: bigint;
}): {
    id: string;
    issueType: string;
    suggestedAction: string;
    description: string;
    timestamp: bigint;
    category: RiskCategory;
    severity: string;
    riskScore: bigint;
} {
    return {
        id: value.id,
        issueType: value.issueType,
        suggestedAction: value.suggestedAction,
        description: value.description,
        timestamp: value.timestamp,
        category: from_candid_RiskCategory_n39(_uploadFile, _downloadFile, value.category),
        severity: value.severity,
        riskScore: value.riskScore
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    usAIRegulations: null;
} | {
    euAIAct: null;
}): Regulation {
    return "usAIRegulations" in value ? Regulation.usAIRegulations : "euAIAct" in value ? Regulation.euAIAct : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): RiskCategory {
    return "low" in value ? RiskCategory.low : "high" in value ? RiskCategory.high : "medium" in value ? RiskCategory.medium : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DocumentMetadata>): Promise<Array<DocumentMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DocumentMetadata_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RepositoryMetadata>): Array<RepositoryMetadata> {
    return value.map((x)=>from_candid_RepositoryMetadata_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RiskEvent>): Array<RiskEvent> {
    return value.map((x)=>from_candid_RiskEvent_n37(_uploadFile, _downloadFile, x));
}
function to_candid_AIActQuery_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AIActQuery): _AIActQuery {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_CybersecurityQuery_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CybersecurityQuery): _CybersecurityQuery {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Regulation_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Regulation): _Regulation {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    context?: string;
    question: string;
}): {
    context: [] | [string];
    question: string;
} {
    return {
        context: value.context ? candid_some(value.context) : candid_none(),
        question: value.question
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Regulation): {
    usAIRegulations: null;
} | {
    euAIAct: null;
} {
    return value == Regulation.usAIRegulations ? {
        usAIRegulations: null
    } : value == Regulation.euAIAct ? {
        euAIAct: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
